###############################################################################
# Alarm System Package for Home Assistant

###############################################################################
# Customization
homeassistant:
  customize:

    # Alarm Control Panel
    alarm_control_panel.ha_alarm:
      icon: mdi:shield-home

###############################################################################
# Entity Groups
group:

  security:
    name: Security
    icon: mdi:security-home
    view: yes
    entities:
      - group.alarms
      - group.doors
      - group.motion

  alarms:
    name: Alarms
    icon: mdi:security
    view: no
    entities:
      - alarm_control_panel.ha_alarm

  doors:
    name: Doors
    icon: mdi:door
    view: no
    entities:
      - binary_sensor.zw_front_door_sensor

  motion:
    name: Motion
    icon: mdi:walk
    view: no
    entities:
      - binary_sensor.zp3111_bedroom_motion
      - binary_sensor.zp3111_kitchen_motion
      - binary_sensor.zse40_living_room_motion

###############################################################################
# Manual MQTT Control Panel
alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    code: !secret alarm_code

###############################################################################
# Binary Sensors for UI
binary_sensor:

  - platform: template
    sensors:

      ## Door Sensors
      doors:
        friendly_name: Doors
        device_class: door
        entity_id: group.doors
        value_template: "{{ is_state('group.doors', 'on') }}"
        icon_template: >-
          {% if is_state('group.doors', 'on') %}
            fas:door-open
          {% elif is_state('group.doors', 'off') %}
            fas:door-closed         
          {% else %}
            mdi:alert
          {% endif %}

      ## Alarm Status Sensor
      alarm:
        friendly_name: Alarm
        entity_id: alarm_control_panel.ha_alarm
        value_template: >-
          {% if is_state('alarm_control_panel.ha_alarm', 'armed_home') %}
            on
          {% elif is_state('alarm_control_panel.ha_alarm', 'armed_away') %}
            on
          {% elif is_state('alarm_control_panel.ha_alarm', 'pending') %}
            on
          {% elif is_state('alarm_control_panel.ha_alarm', 'triggered') %}
            on
          {% else %}
            off
          {% endif %}
        icon_template: >-
          {% if is_state('alarm_control_panel.ha_alarm', 'armed_home') %}
            mdi:shield-home
          {% elif is_state('alarm_control_panel.ha_alarm', 'armed_away') %}
            mdi:shield-lock
          {% elif is_state('alarm_control_panel.ha_alarm', 'pending') %}
            mdi:security
          {% elif is_state('alarm_control_panel.ha_alarm', 'triggered') %}
            mdi:shield-close
          {% elif is_state('alarm_control_panel.ha_alarm', 'disarmed') %}
            mdi:shield-home
          {% else %}
            mdi:alert
          {% endif %}
