###############################################################################
# Alarm System Package for Home Assistant

###############################################################################
# Customization
homeassistant:
  customize:

###############################################################################
# Manual MQTT Control Panel
alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    code: !secret alarm_code
