###############################################################################
# Belkin WeMo Package for Home Assistant

###############################################################################
# Customization
homeassistant:
  customize:

###############################################################################
# Setup WeMo Devices
wemo:
  discovery: true
  static:
    - !secret logi_switch_ip
    - !secret xmas_tree_ip
