language: python
python:
  - "3.5"
install:
  - "pip install homeassistant"
  - "python $TRAVIS_BUILD_DIR/bin/dummy_secrets.py"
  - "sudo mkdir -p /srv/hass && sudo cp $TRAVIS_BUILD_DIR/bin/network-ca-chain.pem /srv/hass/"
  - "sudo mkdir /srv/hass/adb && sudo touch /srv/hass/adb/adbkey"
script: "bash $TRAVIS_BUILD_DIR/bin/check_config.sh"
notifications:
  email: false
branches:
  only:
    - staging
