language: python
python:
  - "3.5"
install:
  - "pip install homeassistant"
  - "python $TRAVIS_BUILD_DIR/bin/dummy_secrets.py"
script: "bash $TRAVIS_BUILD_DIR/bin/check_config.sh"
notifications:
  email: false
branches:
  only:
    - staging
