language: python
python:
  - "3.7"
install:
  - "pip install homeassistant==0.100.2"
  - "python $TRAVIS_BUILD_DIR/bin/dummy_secrets.py"
  - "sudo mkdir /config && sudo cp $TRAVIS_BUILD_DIR/bin/fake-ca.pem /config/network-ca-chain.pem"
script: "bash $TRAVIS_BUILD_DIR/bin/check_config.sh"
notifications:
  email: false
branches:
  only:
    - staging
    - dev
