- id: '1546805510786'
  alias: Front Door Open
  trigger:
  - entity_id: binary_sensor.front_door_open
    for: 0:02:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Door's Open, Yo
    service: notify.telegram_bot
- id: '1546810384290'
  alias: Front Door Departure Scan
  trigger:
  - entity_id: binary_sensor.front_door_open
    for: 0:00:30
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      payload: zw_front_door
      topic: monitor/scan/DEPART
    service: mqtt.publish
- id: '1546811460064'
  alias: Left Home
  trigger:
  - entity_id: binary_sensor.jp_presence
    for: 0:00:30
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: k bye lol
    service: notify.telegram_bot
  - data: {}
    service: light.turn_off
- id: '1546814236876'
  alias: Arrived Home
  trigger:
  - entity_id: binary_sensor.jp_presence
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Welcome home!
    service: notify.telegram_bot
  - data:
      entity_id: light.hue_ambiance_lamp_1
    service: light.turn_on
