- id: '1546805510786'
  alias: Front Door Open
  trigger:
  - entity_id: binary_sensor.front_door_open
    for: 0:05:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Door's Open, Yo
    service: notify.telegram_bot
