###############################################################################
#
# Home Assistant Configuration for the KraussNet 
# 
###############################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude # dummy: 0.0
  longitude: !secret home_longitude # dummy: 0.0
  elevation: 45
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages
  internal_url: !secret http_internal_url
  external_url: !secret http_external_url
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 10.1.0.10
        - 10.1.0.13
        - 10.1.1.21
        - 10.2.1.11

# Lovelace UI in YAML Mode
lovelace:
  mode: yaml
  resources:
    - url: /local/custom_ui/auto-entities.js?v=16
      type: module
    - url: /local/custom_ui/button-card.js?v=3.3.6
      type: module
    - url: /local/custom_ui/custom-header.js?v=1.6.5
      type: module
    - url: /local/custom_ui/layout-card.js?v=16
      type: module
    - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.9.3
      type: module
    - url: /local/custom_ui/mini-media-player-bundle.js?v=1.9.1
      type: module
    - url: /local/custom_ui/text-element.js?v=0.0.2
      type: module
    - url: /local/custom_ui/vertical-stack-in-card.js?v=0.3.3
      type: js

  # Dashboards
  dashboards:
    dashboard-main:
      mode: yaml
      filename: ui-dashboard-main.yaml
      title: Dashboard Main

# MQTT Broker Connection
mqtt:
  broker: mqtt.ha.kraussnet.com
  port: 8883
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /config/network-ca-chain.pem
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Logging
logger:
  default: info

# InfluxDB Logging
influxdb:
  host: !secret influxdb_host
  database: home_assistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  default_measurement: state
  tags_attributes:
    - friendly_name

# API Access for Dashing
http:
#  api_password: !secret http_password
#  base_url: !secret http_base_url
  ip_ban_enabled: false
  login_attempts_threshold: 2

###############################################################################
#
# Customize Default Integrations
# 
# Not Enabled:
#   - cloud
#   - mobile_app
# 
###############################################################################

# Automation File for Configuration UI
automation:

# Enable the Configuration UI
config:

# Enable the Front End
frontend:

  # Add Themes
  themes: !include_dir_merge_named themes

# Configure FontAwesome Icons
fontawesome:
  regular:
  solid:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Enable Person entities for device tracker grouping
# NOTE: See declaration in Presence package
#person:

# Enable support for Simple Service Discovery Protocol
# Used by Philips Hue (disable if moving to Zigbee)
ssdp:

# Track the sun
sun:

# System Health monitor
system_health:

# Checks for Updates
updater:

# Enable UPnP/Zeroconf Service Discovery and Advertising
zeroconf:

# Discover some devices automatically
discovery:

###############################################################################
#
# Include Files
#
###############################################################################

zone: !include include/zones.yaml

#script: !include config/scripts.yaml
#sensor: !include config/sensors.yaml
#input_boolean: !include config/input_booleans.yaml
#input_select: !include config/input_selects.yaml
