###############################################################################
#
# Home Assistant Configuration for the KraussNet 
# 
###############################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude # dummy: 0.0
  longitude: !secret home_longitude # dummy: 0.0
  elevation: 45
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages
  internal_url: !secret http_internal_url
  external_url: !secret http_external_url
  auth_mfa_modules:
    - type: totp
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - !secret lan_net_ip4
        - !secret lan_net_ip6

# Lovelace UI in YAML Mode
lovelace:
  mode: yaml
  resources:
    - url: /local/custom_ui/auto-entities.js?v=16
      type: module
    - url: /local/custom_ui/button-card.js?v=3.3.6
      type: module
    - url: /local/custom_ui/card-mod.js?v=2.0.3
      type: module
    - url: /local/custom_ui/custom-header.js?v=1.6.5
      type: module
    - url: /local/custom_ui/layout-card.js?v=16
      type: module
    - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.9.3
      type: module
    - url: /local/custom_ui/mini-media-player-bundle.js?v=1.9.1
      type: module
    - url: /local/custom_ui/popup-backdrop-filter.js?v=1
      type: module
    - url: /local/custom_ui/text-element.js?v=0.0.2
      type: module
    - url: /local/custom_ui/vertical-stack-in-card.js?v=0.3.3
      type: js

  # Dashboards
  dashboards:
    dashboard-main:
      mode: yaml
      filename: ui-dashboard-main.yaml
      title: Dashboard Main
    livingroom-scenes:
      mode: yaml
      filename: ui-dashboard-lr-scenes.yaml
      show_in_sidebar: true
      title: Living Room Scenes

# MQTT Broker Connection
mqtt:
  broker: mqtt.ha.kraussnet.com
  port: 8883
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /config/network-ca-chain.pem
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Logging
logger:
  default: info

# InfluxDB Logging
influxdb:
  api_version: '1'
  host: !secret influxdb_host
  database: home_assistant
  measurement_attr: domain__device_class
  default_measurement: state
  precision: ms
  tags_attributes:
    - friendly_name
  exclude:
    domains:
      - automation
      - device_tracker
      - group
      - input_boolean
      - input_select
      - media_player
      - scene
      - script
      - zone

# HTTP Access
http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_ip4
    - !secret proxy_ip6
    - !secret gateway_ip4

###############################################################################
#
# Customize Default Integrations
# 
# Not Enabled:
#   - cloud
#   - mobile_app
# 
###############################################################################

# Automation File for Configuration UI
automation:

# Enable the Configuration UI
config:

# Enable the Front End
frontend:

  # Add Themes
  themes: !include_dir_merge_named themes

# Enable Browser_Mod
browser_mod:

# Configure FontAwesome Icons
fontawesome:
  regular:
  solid:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Enable Person entities for device tracker grouping
# NOTE: See declaration in Presence package
#person:

# Enable support for Simple Service Discovery Protocol
# Used by Philips Hue (disable if moving to Zigbee)
ssdp:

# Track the sun
sun:

# System Health monitor
system_health:

# Checks for Updates
updater:

# Enable UPnP/Zeroconf Service Discovery and Advertising
zeroconf:

# Discover some devices automatically
discovery:

###############################################################################
#
# Include Files
#
###############################################################################

zone: !include include/zones.yaml

#script: !include config/scripts.yaml
#sensor: !include config/sensors.yaml
#input_boolean: !include config/input_booleans.yaml
#input_select: !include config/input_selects.yaml
