###############################################################################
#
# Home Assistant Configuration for the KraussNet 
# 
###############################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude # dummy: 0.0
  longitude: !secret home_longitude # dummy: 0.0
  elevation: 45
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 10.1.0.10
        - 10.1.0.13
        - 10.1.1.21
        - 10.2.1.11

# Lovelace UI in YAML Mode
lovelace:
  mode: yaml

# MQTT Broker Connection
mqtt:
  broker: mqtt.ha.kraussnet.com
  port: 8883
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /config/network-ca-chain.pem
  tls_version: '1.2'
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Logging
logger:
  default: info

# API Access for Dashing
http:
#  api_password: !secret http_password
  ip_ban_enabled: false
  login_attempts_threshold: 2

###############################################################################
#
# Customize Default Integrations
# 
# Not Enabled:
#   - cloud
#   - mobile_app
# 
###############################################################################

# Automation File for Configuration UI
automation:

# Enable the Configuration UI
config:

# Enable the Front End
frontend:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Enable Person entities for device tracker grouping
person:

# Enable support for Simple Service Discovery Protocol
# Used by Philips Hue (disable if moving to Zigbee)
ssdp:

# Track the sun
sun:

# System Health monitor
system_health:

# Checks for Updates
updater:

# Enable UPnP/Zeroconf Service Discovery and Advertising
zeroconf:

# Discover some devices automatically
discovery:

###############################################################################
#
# Z-Wave
#
###############################################################################

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_net_key

###############################################################################
#
# Include Files
#
###############################################################################

zone: !include include/zones.yaml

#script: !include config/scripts.yaml
#sensor: !include config/sensors.yaml
#input_boolean: !include config/input_booleans.yaml
#input_select: !include config/input_selects.yaml
