# Home Assistant Configuration for the KraussNet
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 45
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

# MQTT Broker Connection
mqtt:
  broker: mqtt.ha.snrhome.com
  port: 8883
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /srv/hass/config/network-ca-chain.pem
  tls_version: '1.2'
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Logging
logger:
  default: warning
  logs:
    homeassistant.components.http: warning
    homeassistant.components.mqtt: debug

# API Access for Dashing
http:
  api_password: !secret http_password
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 10.0.1.0/24
    - 10.0.2.0/24

# Enable the Front End
frontend:

# Enable the Configuration UI
config:

# Checks for Updates
updater:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Telegram Notifier
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id # dummy: 1234567

# Notifiers
notify:
  - name: telegram_bot
    platform: telegram
    chat_id: !secret telegram_chat_id
  
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

# Node-Red IFrame
panel_iframe:
  nodered:
    title: 'Node-Red'
    icon: mdi:shuffle-variant
    url: 'http://localhost:1880'

# Device Tracking
device_tracker:

  # Track WiFi with Tomato Router/AP
  - platform: tomato
    host: 10.0.2.253
    username: !secret tomato_username
    password: !secret tomato_password
    http_id: !secret tomato_http_id
    interval_seconds: 10
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
      hide_if_away: true

  # Track with Built-In Bluetooth
  #- platform: bluetooth_tracker
  #  request_rssi: true
  #  new_device_defaults:
  #    track_new_devices: false
  #    hide_if_away: false

# FireTV and Kodi Media Players
media_player:
  - platform: firetv
    name: Living Room FireTV
    host: 10.0.1.91
    adbkey: /srv/hass/adb/adbkey

# OwnTracks Setup
owntracks:
  max_gps_accuracy: 50
  waypoints: true
  mqtt_topic: 'owntracks/#'
  events_only: false
  waypoint_whitelist:
    - jp
  region_mapping:
    Home: home
    Work: work

# Include Files
group: !include config/groups.yaml
automation: !include config/automations.yaml
scene: !include config/scenes.yaml
script: !include config/scripts.yaml
sensor: !include config/sensors.yaml
switch: !include config/switches.yaml
binary_sensor: !include config/binary_sensors.yaml
input_select: !include config/input_selects.yaml

