#### Home Assistant Configuration for the KraussNet ###########################
homeassistant:
  name: Home
  latitude: !secret home_latitude # dummy: 0.0
  longitude: !secret home_longitude # dummy: 0.0
  elevation: 45
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

# Lovelace UI in YAML Mode
lovelace:
  mode: yaml

# MQTT Broker Connection
mqtt:
  broker: mqtt.ha.kraussnet.com
  port: 8883
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /config/network-ca-chain.pem
  tls_version: '1.2'
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Logging
logger:
  default: warning

# API Access for Dashing
http:
  api_password: !secret http_password
  ip_ban_enabled: true
  login_attempts_threshold: 2
  trusted_networks:
    - 127.0.0.1
    - 10.1.0.13
    - 10.1.1.21
    - 10.2.1.11
    
# Enable the Front End
frontend:

# Enable the Configuration UI
config:

# Checks for Updates
updater:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# System Health monitor
system_health:
        
# Telegram Notifier
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id # dummy: 1234567

# Notifiers
notify:
  - name: telegram_bot
    platform: telegram
    chat_id: !secret telegram_chat_id

# Node-Red IFrame
panel_iframe:
  nodered:
    title: 'Node-Red'
    icon: mdi:shuffle-variant
    url: 'http://nodered.ha.kraussnet.com:1880'

# Device Tracking
device_tracker:

  # Track WiFi with UniFi AP
  - platform: unifi
    host: unifi.mgmt.kraussnet.com
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    interval_seconds: 10
    consider_home: 60
    detection_time: 60                # consider_home synonym for UniFi
    new_device_defaults:
      track_new_devices: false
      hide_if_away: true

# FireTV and Kodi Media Players
media_player:
  - platform: androidtv
    name: Living Room FireTV
    host: 10.1.2.11
    adbkey: /config/adb/adbkey

  - platform: kodi
    name: Living Room OSMC
    host: 10.1.2.12
    port: 80

# OwnTracks Setup
owntracks:
  max_gps_accuracy: 50
  waypoints: true
  mqtt_topic: 'owntracks/#'
  events_only: false
  waypoint_whitelist:
    - jp
  region_mapping:
    Home: home
    Work: work

# InfluxDB Configuration
influxdb:
  host: influx.ha.kraussnet.com
  port: 8086
  database: home_assistant
  tags:
    source: hass
    instance: !secret influxdb_instance   # dummy: dev

# WeMo Components
wemo:
  discovery: false
  static:
    - 10.2.1.241
    - 10.2.1.242
    - 10.2.1.243

# Automation File for Configuration UI
automation: !include automations.yaml

# Include Files
group: !include config/groups.yaml
light: !include config/lights.yaml
scene: !include config/scenes.yaml
script: !include config/scripts.yaml
sensor: !include config/sensors.yaml
switch: !include config/switches.yaml
binary_sensor: !include config/binary_sensors.yaml
input_boolean: !include config/input_booleans.yaml
input_select: !include config/input_selects.yaml
