###############################################################################
# Lovelace UI Configuration for Home Assistant

button_card_templates:
  area_scene:
    show_icon: false
    show_state: false
    show_name: true
    styles:
      card:
        - 'border-top': '1px solid var(--divider-color)'
        - 'padding-top': '0.5em'
    tap_action:
      action: call-service
      service: scene.turn_on
      service_data:
        entity_id: '[[[ return entity.entity_id ]]]'
        transition: 3

###############################################################################
###
### Main Dashboard

title: Krauss Home
views:

###############################################################################
###
### Main Dashboard View

  - id: 0
    icon: mdi:home
    title: Home
    cards:

      #########################################################################
      # Alarm and Alert Sensors
      - type: entities
        entities:
          - binary_sensor.alarm
          - binary_sensor.doors

      #########################################################################
      # Presence Status
      - type: custom:vertical-stack-in-card
        cards:

          - type: glance
            entities:
              - person.jpk
              - person.jen

          - type: horizontal-stack
            cards:
              - type: glance
                show_name: false
                entities:
                  - device_tracker.jp_p3a_ip
                  - device_tracker.jp_p3a_bt_entry
                  - device_tracker.jp_p3a_gps

              - type: glance
                show_name: false
                entities:
                  - device_tracker.jen_iphone_ip
                  - device_tracker.jen_iphone_bt_entry

      #########################################################################
      # Areas
      - type: custom:vertical-stack-in-card
        cards:
          - type: area
            area: 130b3aba5ba74ebf898cea9c5f2fdef9    # Living Room

          - type: custom:vertical-stack-in-card
            horizontal: true
            cards:
              - type: custom:button-card
                name: Full
                entity: scene.living_room_normal
                template: area_scene

              - type: custom:button-card
                name: Low
                entity: scene.living_room_low
                template: area_scene

              - type: custom:button-card
                name: Dim
                entity: scene.living_room_dim
                template: area_scene

          - type: custom:vertical-stack-in-card
            horizontal: true
            cards:
              - type: custom:button-card
                name: TV Normal
                entity: scene.tv_normal
                template: area_scene

              - type: custom:button-card
                name: Reading - Back
                entity: scene.reading_back
                template: area_scene

              - type: custom:button-card
                name: Reading - Entry
                entity: scene.reading_entry
                template: area_scene

      - type: custom:vertical-stack-in-card
        cards:
          - type: area
            area: dining_room

          - type: custom:vertical-stack-in-card
            horizontal: zse40_living_room_temperature
            cards:
              - type: custom:button-card
                name: Full
                entity: scene.dining_room_normal
                template: area_scene

              - type: custom:button-card
                name: Low
                entity: scene.dining_room_low
                template: area_scene

              - type: custom:button-card
                name: Dim
                entity: scene.dining_room_dim
                template: area_scene

      - type: area
        area: 95cfad3ed8724e9fb9536dd6dee2ff70    # Bedroom

      #########################################################################
      # Lighting


      #########################################################################
      # Weather
      - type: weather-forecast
        entity: weather.owm
        show_forecast: false
        secondary_info_attribute: humidity

      # #########################################################################
      # # Media Players
      # - type: horizontal-stack
      #   cards:
      #     #- type: custom:mini-media-player
      #     #  entity: media_player.living_room_osmc
      #     #  info: short
      #     #  artwork: cover
      #     #  hide:
      #     #    mute: true
      #     #    icon: true
      #     #    power_state: false

      #     - type: custom:mini-media-player
      #       entity: media_player.roku_ultra
      #       info: short
      #       artwork: cover
      #       hide:
      #         mute: true
      #         icon: true
      #         power_state: false

      #     - type: custom:mini-media-player
      #       entity: media_player.mpd
      #       info: short
      #       artwork: cover
      #       hide:
      #         mute: true
      #         icon: true
      #         power_state: false

      # - type: entities
      #   title: Media Center
      #   entities:
      #     - input_select.ht_lighting_mode

###############################################################################
###
### Alarm Status View

  - id: 1
    icon: mdi:security
    title: Security
    cards:

      #########################################################################
      # Alarm Panel
      - type: alarm-panel
        entity: alarm_control_panel.ha_alarm

      #########################################################################
      # Door Sensor Status
      - type: custom:auto-entities
        card:
          type: glance
          title: Doors
        filter:
          include:
            - group: group.doors

      #########################################################################
      # Motion Sensor Status
      - type: custom:auto-entities
        card:
          type: glance
          title: Motion
        filter:
          include:
            - group: group.motion

      #########################################################################
      # Camera Status
      - type: glance
        title: Logi Circle 2
        entities:
          - binary_sensor.camera_switch_issue
          - binary_sensor.camera_switch
          - binary_sensor.logi_circle_switch
          - binary_sensor.logi_circle_camera

###############################################################################
###
### Home Audio System

  - icon: mdi:speaker
    title: Home Audio
    cards:

      #########################################################################
      # Snapcast Client/Group Setup
      - type: entities
        title: Snapcast Control
        show_header_toggle: false
        entities:
          - entity: media_player.snapcast_group_home
            type: 'custom:mini-media-player'
            group: true
            hide:
              power: true
              icon: true
            info: short
            speaker_group:
              platform: snapcast
              show_group_count: true
              entities:
                - entity_id: media_player.snapcast_client_stereo
                  name: Living Room Stereo
                - entity_id: media_player.snapcast_client_office
                  name: Office Workstation

###############################################################################
###
### Holiday / Special Events View

  - icon: fas:holly-berry
    title: Holiday
    cards:

      #########################################################################
      # Christmas Lights
      - type: entities
        title: Christmas
        show_header_toggle: true
        entities:
          - switch.christmas_tree

###############################################################################
###
### Climate Control

  - icon: fas:temperature-high
    title: Climate
    cards:

      #########################################################################
      # Climate
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.zp3111_bedroom_temperature
            name: Bedroom
            line_color: '#2980b9'
            line_width: 6

          - type: custom:mini-graph-card
            entities:
              - sensor.zse40_office_temperature
            name: Office
            line_color: '#b93829'
            line_width: 6

      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.zp3111_kitchen_temperature
            name: Kitchen
            line_color: '#b58e31'
            line_width: 6

          - type: custom:mini-graph-card
            entities:
              - sensor.zse40_living_room_temperature
            name: Living Room
            line_color: '#b93829'
            line_width: 6

      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.zse40_garage_temperature
            name: Garage
            line_color: '#b58e31'
            line_width: 6

###############################################################################
###
### Advanced Utilities View

  - icon: mdi:dip-switch
    title: Advanced
    cards:
      - type: entities
        title: Bluetooth Presence Monitor
        show_header_toggle: false
        entities:
          - type: call-service
            icon: mdi:refresh
            name: Departure Scan
            action_name: Run Scan
            service: mqtt.publish
            service_data:
              topic: monitor/scan/depart
              payload: start

      - type: entities
        title: Restart NUT
        show_header_toggle: false
        entities:
          - type: call-service
            icon: mdi:refresh
            name: Restart NUT
            action_name: Restart
            service: monitor_docker.restart
            service_data:
              name: nut
