###############################################################################
# Lovelace UI Configuration for Home Assistant

title: Krauss Home
views:

###############################################################################
###
### Main Dashboard View

  - id: 0
    icon: mdi:home
    title: Home
    cards:

      #########################################################################
      # Alarm and Alert Sensors
      - type: entities
        entities:
          - binary_sensor.alarm
          - binary_sensor.doors

      #########################################################################
      # Presence Status
      - type: custom:vertical-stack-in-card
        cards:

          - type: glance
            entities:
              - person.jpk
              - person.jen

          - type: horizontal-stack
            cards:
              - type: glance
                show_name: false
                entities:
                  - device_tracker.jp_p3a_ip
                  - device_tracker.jp_p3a_bt_entry
                  - device_tracker.jp_p3a_gps

              - type: glance
                show_name: false
                entities:
                  - device_tracker.jen_iphone_ip
                  - device_tracker.jen_iphone_bt_entry

      #########################################################################
      # Areas
      - type: custom:vertical-stack-in-card
        cards:
          - type: area
            area: 130b3aba5ba74ebf898cea9c5f2fdef9    # Living Room

          - type: custom:vertical-stack-in-card
            horizontal: true
            cards:
              - type: button
                name: Full
                show_icon: false
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_room_normal
                    transition: 3

              - type: button
                name: Low
                show_icon: false
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_room_low
                    transition: 3

              - type: button
                name: Dim
                show_icon: false
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_room_dim
                    transition: 3

      - type: area
        area: dining_room

      #########################################################################
      # Lighting
      - type: custom:vertical-stack-in-card
        cards:
          - type: button
            entity: light.living_room_lights
            name: Living Room
            icon_height: 40px

          - type: custom:vertical-stack-in-card
            horizontal: true
            cards:
              - type: button
                name: Full
                show_icon: false
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_room_normal
                    transition: 3

              - type: button
                name: Low
                show_icon: false
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_room_low
                    transition: 3

              - type: button
                name: Dim
                show_icon: false
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_room_dim
                    transition: 3

      - type: custom:vertical-stack-in-card
        cards:
          - type: button
            entity: light.dining_room_lights
            name: Dining Room
            icon_height: 40px

          - type: custom:vertical-stack-in-card
            horizontal: true
            cards:
              - type: button
                name: Full
                show_icon: false
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.dining_room_normal
                    transition: 3

              - type: button
                name: Low
                show_icon: false
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.dining_room_low
                    transition: 3

              - type: button
                name: Dim
                show_icon: false
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.dining_room_dim
                    transition: 3

      # #########################################################################
      # # Bedroom Room Card
      # - type: custom:vertical-stack-in-card
      #   cards:
      #     # Header
      #     - type: picture-elements
      #       image: /local/custom_ui/img/title-dark.png
      #       elements:
      #         # Title
      #         - type: custom:text-element
      #           text: Bedroom
      #           style:
      #             color: white
      #             font-size: 175%
      #             left: 5%
      #             top: 35%
      #             transform: initial

      #         # Glance Slot #4
      #         - type: state-icon
      #           entity: binary_sensor.zp3111_bedroom_motion
      #           style:
      #             color: white
      #             right: 16%
      #             top: 15%
      #             transform: initial

      #         # Temperature Slot
      #         - type: state-label
      #           entity: sensor.zp3111_bedroom_temperature
      #           style:
      #             color: white
      #             right: 2%
      #             top: 21%
      #             transform: initial

      #     # Card Body
      #     - type: picture-elements
      #       image: /local/custom_ui/img/background200.png
      #       elements:
      #         # Temperature Graph
      #         - type: custom:mini-graph-card
      #           upper_bound: 100
      #           lower_bound: 60
      #           line_width: 0.5
      #           entities:
      #             - entity: sensor.zp3111_bedroom_temperature
      #               index: 0
      #           height: 202
      #           show:
      #             icon: false
      #             name: false
      #             state: false
      #           style:
      #             right: -50%
      #             top: 47%
      #             width: 100%

      #         # Button #1
      #         - type: custom:button-card
      #           color: auto
      #           entity: light.zb_bedroom_jen
      #           show_name: false
      #           style:
      #             left: 12%
      #             top: 32%
      #           styles:
      #             card:
      #               - border-radius: 50px
      #               - width: 50px
      #               - height: 50px
      #             icon:
      #               - width: 30px
      #               - height: 30px
      #           tap_action:
      #             action: more-info

      #         - type: custom:text-element
      #           style:
      #             left: 12%
      #             top: 60%
      #           text: Jen

      #         # Button #2
      #         - type: custom:button-card
      #           color: auto
      #           entity: light.zb_bedroom_jp
      #           show_name: false
      #           style:
      #             left: 31%
      #             top: 32%
      #           styles:
      #             card:
      #               - border-radius: 50px
      #               - width: 50px
      #               - height: 50px
      #             icon:
      #               - width: 30px
      #               - height: 30px
      #           tap_action:
      #             action: more-info

      #         - type: custom:text-element
      #           style:
      #             left: 31%
      #             top: 60%
      #           text: J.P.

      #########################################################################
      # Weather
      - type: weather-forecast
        entity: weather.owm
        show_forecast: false
        secondary_info_attribute: humidity

      # #########################################################################
      # # Media Players
      # - type: horizontal-stack
      #   cards:
      #     #- type: custom:mini-media-player
      #     #  entity: media_player.living_room_osmc
      #     #  info: short
      #     #  artwork: cover
      #     #  hide:
      #     #    mute: true
      #     #    icon: true
      #     #    power_state: false

      #     - type: custom:mini-media-player
      #       entity: media_player.roku_ultra
      #       info: short
      #       artwork: cover
      #       hide:
      #         mute: true
      #         icon: true
      #         power_state: false

      #     - type: custom:mini-media-player
      #       entity: media_player.mpd
      #       info: short
      #       artwork: cover
      #       hide:
      #         mute: true
      #         icon: true
      #         power_state: false

      # - type: entities
      #   title: Media Center
      #   entities:
      #     - input_select.ht_lighting_mode

###############################################################################
###
### Alarm Status View

  - id: 1
    icon: mdi:security
    title: Security
    cards:

      #########################################################################
      # Alarm Panel
      - type: alarm-panel
        entity: alarm_control_panel.ha_alarm

      #########################################################################
      # Door Sensor Status
      - type: custom:auto-entities
        card:
          type: glance
          title: Doors
        filter:
          include:
            - group: group.doors

      #########################################################################
      # Motion Sensor Status
      - type: custom:auto-entities
        card:
          type: glance
          title: Motion
        filter:
          include:
            - group: group.motion

      #########################################################################
      # Camera Status
      - type: glance
        title: Logi Circle 2
        entities:
          - binary_sensor.camera_switch_issue
          - binary_sensor.camera_switch
          - binary_sensor.logi_circle_switch
          - binary_sensor.logi_circle_camera

###############################################################################
###
### Home Audio System

  - icon: mdi:speaker
    title: Home Audio
    cards:

      #########################################################################
      # Snapcast Client/Group Setup
      - type: entities
        title: Snapcast Control
        show_header_toggle: false
        entities:
          - entity: media_player.snapcast_group_home
            type: 'custom:mini-media-player'
            group: true
            hide:
              power: true
              icon: true
            info: short
            speaker_group:
              platform: snapcast
              show_group_count: true
              entities:
                - entity_id: media_player.snapcast_client_stereo
                  name: Living Room Stereo
                - entity_id: media_player.snapcast_client_office
                  name: Office Workstation

###############################################################################
###
### Holiday / Special Events View

  - icon: fas:holly-berry
    title: Holiday
    cards:

      #########################################################################
      # Christmas Lights
      - type: entities
        title: Christmas
        show_header_toggle: true
        entities:
          - switch.christmas_tree

###############################################################################
###
### Climate Control

  - icon: fas:temperature-high
    title: Climate
    cards:

      #########################################################################
      # Climate
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.zp3111_bedroom_temperature
            name: Bedroom
            line_color: '#2980b9'
            line_width: 6

          - type: custom:mini-graph-card
            entities:
              - sensor.zse40_office_temperature
            name: Office
            line_color: '#b93829'
            line_width: 6

      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.zp3111_kitchen_temperature
            name: Kitchen
            line_color: '#b58e31'
            line_width: 6

          - type: custom:mini-graph-card
            entities:
              - sensor.zse40_living_room_temperature
            name: Living Room
            line_color: '#b93829'
            line_width: 6

      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.zse40_garage_temperature
            name: Garage
            line_color: '#b58e31'
            line_width: 6

###############################################################################
###
### Advanced Utilities View

  - icon: mdi:dip-switch
    title: Advanced
    cards:
      - type: entities
        title: Bluetooth Presence Monitor
        show_header_toggle: false
        entities:
          - type: call-service
            icon: mdi:refresh
            name: Departure Scan
            action_name: Run Scan
            service: mqtt.publish
            service_data:
              topic: monitor/scan/depart
              payload: start

      - type: entities
        title: Restart NUT
        show_header_toggle: false
        entities:
          - type: call-service
            icon: mdi:refresh
            name: Restart NUT
            action_name: Restart
            service: monitor_docker.restart
            service_data:
              name: nut
