###############################################################################
# Lovelace UI Configuration for Home Assistant

title: Krauss Home

###############################################################################
# Resource Imports
resources:
  - url: /local/custom_ui/auto-entities.js?v=16
    type: module
  - url: /local/custom_ui/custom-header.js?v=1.6.5
    type: module
  - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.9.3
    type: module
  - url: /local/custom_ui/mini-media-player-bundle.js?v=1.9.1
    type: module
  - url: /local/custom_ui/vertical-stack-in-card.js?v=0.3.3
    type: js

###############################################################################
# Compact Custom Header Configuration
custom_header:
  compact_mode: true
  menu_hide: false
  voice_hide: true
  button_text:
    options: '{{ hours12 }}:{{ minutesLZ }}'

views:

###############################################################################
###
### Main Dashboard View

  - id: 0
    icon: mdi:home
    title: Home
    cards:

      #########################################################################
      # Alarm and Alert Sensors
      - type: entities
        entities:
          - binary_sensor.alarm
          - binary_sensor.doors

      #########################################################################
      # Presence Status
      - type: custom:vertical-stack-in-card
        cards:

          - type: glance
            entities:
              - person.jpk
              - person.jen

          - type: horizontal-stack
            cards:
              - type: glance
                show_name: false
                entities:
                  - device_tracker.jp_p3a_ap
                  - device_tracker.jp_p3a_bt_entry
                  - device_tracker.jp_p3a_gps

              - type: glance
                show_name: false
                entities:
                  - device_tracker.jen_iphone_ap
                  - device_tracker.jen_iphone_bt_entry

      #########################################################################
      # Lighting
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: light.living_room_lights
            name: Living Room
            double_tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.living_room_normal

          - type: entity-button
            entity: light.dining_room_lights
            name: Dining Room
            double_tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.dining_room_normal

          - type: entity-button
            entity: light.bedroom_lights
            name: Bedroom

      #########################################################################
      # Weather
      - type: weather-forecast
        entity: weather.dark_sky
        show_forecast: false
        secondary_info_attribute: humidity

      #########################################################################
      # Climate
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.zp3111_bedroom_temperature
            name: Bedroom
            line_color: '#2980b9'
            line_width: 6

          - type: custom:mini-graph-card
            entities:
              - sensor.zp3111_kitchen_temperature
            name: Kitchen
            line_color: '#b58e31'
            line_width: 6

          - type: custom:mini-graph-card
            entities:
              - sensor.zse40_living_room_temperature
            name: Living Room
            line_color: '#b93829'
            line_width: 6

      #########################################################################
      # Media Players
      - type: horizontal-stack
        cards:
          #- type: custom:mini-media-player
          #  entity: media_player.living_room_osmc
          #  info: short
          #  artwork: cover
          #  hide:
          #    mute: true
          #    icon: true
          #    power_state: false

          - type: custom:mini-media-player
            entity: media_player.roku
            info: short
            artwork: cover
            hide:
              mute: true
              icon: true
              power_state: false

###############################################################################
###
### Alarm Status View

  - id: 1
    icon: mdi:security
    title: Security
    cards:

      #########################################################################
      # Alarm Panel
      - type: alarm-panel
        entity: alarm_control_panel.ha_alarm

      #########################################################################
      # Door Sensor Status
      - type: custom:auto-entities
        card:
          type: glance
          title: Doors
        filter:
          include:
            - group: group.doors

      #########################################################################
      # Motion Sensor Status
      - type: custom:auto-entities
        card:
          type: glance
          title: Motion
        filter:
          include:
            - group: group.motion

      #########################################################################
      # Camera Status
      - type: glance
        title: Logi Circle 2
        entities:
          - binary_sensor.camera_switch_issue
          - binary_sensor.camera_switch
          - binary_sensor.logi_circle_switch
          - binary_sensor.logi_circle_camera

###############################################################################
###
### Home Audio System

  - icon: mdi:speaker
    title: Home Audio
    cards:

      #########################################################################
      # Snapcast Client/Group Setup
      - type: entities
        title: Snapcast Control
        show_header_toggle: false
        entities:
          - entity: media_player.snapcast_group_home
            type: 'custom:mini-media-player'
            group: true
            hide:
              power: true
              icon: true
            info: short
            speaker_group:
              platform: snapcast
              show_group_count: true
              entities:
                - entity_id: media_player.snapcast_client_stereo
                  name: Living Room Stereo
                - entity_id: media_player.snapcast_client_office
                  name: Office Workstation

###############################################################################
###
### Holiday / Special Events View

  - icon: fas:holly-berry
    title: Holiday
    cards:

      #########################################################################
      # Christmas Lights
      - type: entities
        title: Christmas
        show_header_toggle: true
        entities:
          - switch.christmas_tree

###############################################################################
###
### Advanced Utilities View

  - icon: mdi:dip-switch
    title: Advanced
    cards:
      - type: entities
        title: Bluetooth Presence Monitor
        show_header_toggle: false
        entities:
          - type: call-service
            icon: mdi:refresh
            name: Departure Scan
            action_name: Run Scan
            service: mqtt.publish
            service_data:
              topic: monitor/scan/depart
              payload: start

