#### Lovelace UI Configuration ################################################

title: Krauss Home
resources:
  # Animated DarkSky Card
  - url: /local/custom_ui/dark-sky-weather-card.js
    type: module

views:
  # Legacy UI (groups.yaml) Tab
  - title: Legacy
    badges:
      - binary_sensor.front_door_open
      - binary_sensor.jp_presence
      - device_tracker.jp_n5x_ip
      - device_tracker.jp_n5xot
      - sun.sun
    cards:
      - type: entities
        title: People
        show_header_toggle: false
        entities:
          - sensor.jp_status

      - type: entities
        title: Weather
        show_header_toggle: false
        entities:
          - sensor.dark_sky_summary
          - sensor.dark_sky_temperature

      - type: entities
        title: Device Status
        show_header_toggle: false
        entities:
          - sensor.media_center_status

      - type: entities
        title: Living Room
        entities:
          - light.living_room_front
          - light.living_room_back
          - light.living_room_entry
          - type: divider
            background-color: “#B3B3B3”
          - scene.living_room_normal
          - scene.living_room_dim

      - type: entities
        title: Dining Room
        entities:
          - light.dining_room_1
          - light.dining_room_2
          - light.dining_room_3
          - type: divider
            background-color: “#B3B3B3”
          - scene.dining_room_normal
          - scene.dining_room_low
          - scene.dining_room_dim

      - type: entities
        title: Bedroom
        show_header_toggle: false
        badges:
          - sensor.jp_bed
        entities:
          - light.nightstand_right
          - script.sunrise
          - script.sunset

  # DarkSky Animated Weather Card Dev
  - title: DarkSky
    cards:
      - type: 'custom:dark-sky-weather-card'
        # Required Sensor Entries
        entity_current_conditions: sensor.dark_sky_icon
        entity_temperature: sensor.dark_sky_temperature
        entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
        entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2
        entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3
        entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4
        entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5
        entity_forecast_icon_1: sensor.dark_sky_icon_1
        entity_forecast_icon_2: sensor.dark_sky_icon_2
        entity_forecast_icon_3: sensor.dark_sky_icon_3
        entity_forecast_icon_4: sensor.dark_sky_icon_4
        entity_forecast_icon_5: sensor.dark_sky_icon_5
        entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_0
        entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1
        entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2
        entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3
        entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4
        entity_summary_1: sensor.dark_sky_summary_1
        entity_summary_2: sensor.dark_sky_summary_2
        entity_summary_3: sensor.dark_sky_summary_3
        entity_summary_4: sensor.dark_sky_summary_4
        entity_summary_5: sensor.dark_sky_summary_5
        # Optional Sensor Entries
        entity_sun: sun.sun
        entity_visibility: sensor.dark_sky_visibility
        entity_daytime_high: sensor.dark_sky_daytime_high_temperature_0
        entity_wind_bearing: sensor.dark_sky_wind_bearing
        entity_wind_speed: sensor.dark_sky_wind_speed
        entity_humidity: sensor.dark_sky_humidity
        entity_pressure: sensor.dark_sky_pressure
        entity_apparent_temp: sensor.dark_sky_apparent_temperature
        entity_daily_summary: sensor.dark_sky_daily_summary
        entity_pop: sensor.dark_sky_precip_probability
        entity_pop_intensity: sensor.dark_sky_precip_intensity
        entity_pop_1: sensor.dark_sky_precip_probability_1
        entity_pop_2: sensor.dark_sky_precip_probability_2
        entity_pop_3: sensor.dark_sky_precip_probability_3
        entity_pop_4: sensor.dark_sky_precip_probability_4
        entity_pop_5: sensor.dark_sky_precip_probability_5
        entity_current_text: sensor.dark_sky_current_text
        # Configuration Flags
        locale: en
        static_icons: false
        tooltip_bg_color: 'rgb( 75,155,239)'
        tooltip_border_color: orange
        tooltip_border_width: 3
        tooltip_caret_size: 10
        tooltip_fg_color: '#fff'
        tooltip_left_offset: -12
        tooltip_width: 100
        tooltips: true
        old_daily_format: false
        time_format: 24
        show_beaufort: true
