###############################################################################
# Weather Package for Home Assistant

###############################################################################
# Customization
homeassistant:
  customize:

    # DarkSky Current Sensors
    sensor.dark_sky_humidity:
      friendly_name: Current Humidity
    sensor.dark_sky_temperature:
      friendly_name: Current Temperature

    sensor.dark_sky_apparent_temperature:
      hidden: true
    sensor.dark_sky_current_text:
      hidden: true
    sensor.dark_sky_daily_summary:
      hidden: true
    sensor.dark_sky_icon:
      hidden: true
    sensor.dark_sky_nearest_storm_bearing:
      hidden: true
    sensor.dark_sky_nearest_storm_distance:
      hidden: true
    sensor.dark_sky_precip:
      hidden: true
    sensor.dark_sky_precip_probability:
      hidden: true
    sensor.dark_sky_precip_intensity:
      hidden: true
    sensor.dark_sky_pressure:
      hidden: true
    sensor.dark_sky_summary:
      hidden: true
    sensor.dark_sky_uv_index:
      hidden: true
    sensor.dark_sky_visibility:
      hidden: true
    sensor.dark_sky_wind_bearing:
      hidden: true
    sensor.dark_sky_wind_speed:
      hidden: true

  customize_glob:
    
    # DarkSky Forecast Sensors
    "sensor.dark_sky_*_0d":
      hidden: true
    "sensor.dark_sky_*_1d":
      hidden: true
    "sensor.dark_sky_*_2d":
      hidden: true
    "sensor.dark_sky_*_3d":
      hidden: true
    "sensor.dark_sky_*_4d":
      hidden: true
    "sensor.dark_sky_*_5d":
      hidden: true

###############################################################################
# DarkSky Forecast Card Sensors
sensor:

  # DarkSky Weather Conditions and Forecast
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 5

  # Dark Sky Current Condition
  - platform: template
    sensors:
      dark_sky_current_text:
        value_template: '{% if is_state("sensor.dark_sky_icon","clear-day") %} Clear 
                         {% elif is_state("sensor.dark_sky_icon","clear-night") %} Clear 
                         {% elif is_state("sensor.dark_sky_icon","rain") %} Rain
                         {% elif is_state("sensor.dark_sky_icon","snow") %} Snowy
                         {% elif is_state("sensor.dark_sky_icon","fog") %} Foggy
                         {% elif is_state("sensor.dark_sky_icon","sleet") %} Sleet
                         {% elif is_state("sensor.dark_sky_icon","wind") %} Windy
                         {% elif is_state("sensor.dark_sky_icon","cloudy") %} Cloudy
                         {% elif is_state("sensor.dark_sky_icon","partly-cloudy-day") %} Partly Cloudy
                         {% elif is_state("sensor.dark_sky_icon","partly-cloudy-night") %} Partly Cloudy
                         {% elif is_state("sensor.dark_sky_icon","hail") %} Hailing
                         {% elif is_state("sensor.dark_sky_icon","lightning") %} Lightning
                         {% elif is_state("sensor.dark_sky_icon","thunderstorm") %} Thunderstorm
                         {% endif %}'

###############################################################################
# Exclude Forecast Sensors from History
history:
  exclude:
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_current_text
      - sensor.dark_sky_daily_max_precip_intensity_0d
      - sensor.dark_sky_daily_max_precip_intensity_1d
      - sensor.dark_sky_daily_max_precip_intensity_2d
      - sensor.dark_sky_daily_max_precip_intensity_3d
      - sensor.dark_sky_daily_max_precip_intensity_4d
      - sensor.dark_sky_daily_max_precip_intensity_5d
