###############################################################################
# Weather Package for Home Assistant

###############################################################################
# Customization
homeassistant:
  customize:

    # DarkSky Current Sensors
    sensor.dark_sky_humidity:
      friendly_name: Current Humidity
    sensor.dark_sky_temperature:
      friendly_name: Current Temperature

    sensor.dark_sky_apparent_temperature:
      hidden: true
    sensor.dark_sky_current_text:
      hidden: true
    sensor.dark_sky_daily_summary:
      hidden: true
    sensor.dark_sky_icon:
      hidden: true
    sensor.dark_sky_nearest_storm_bearing:
      hidden: true
    sensor.dark_sky_nearest_storm_distance:
      hidden: true
    sensor.dark_sky_precip:
      hidden: true
    sensor.dark_sky_precip_probability:
      hidden: true
    sensor.dark_sky_precip_intensity:
      hidden: true
    sensor.dark_sky_pressure:
      hidden: true
    sensor.dark_sky_summary:
      hidden: true
    sensor.dark_sky_uv_index:
      hidden: true
    sensor.dark_sky_visibility:
      hidden: true
    sensor.dark_sky_wind_bearing:
      hidden: true
    sensor.dark_sky_wind_speed:
      hidden: true

  customize_glob:
    
    # DarkSky Forecast Sensors
    "sensor.dark_sky_*_0d":
      hidden: true
    "sensor.dark_sky_*_1d":
      hidden: true
    "sensor.dark_sky_*_2d":
      hidden: true
    "sensor.dark_sky_*_3d":
      hidden: true
    "sensor.dark_sky_*_4d":
      hidden: true
    "sensor.dark_sky_*_5d":
      hidden: true

###############################################################################
# DarkSky Forecast Card Sensors
sensor:

  # DarkSky Weather Conditions and Forecast
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 5

  # Dark Sky Current Condition
  - platform: template
    sensors:
      dark_sky_current_text:
        value_template: '{% if is_state("sensor.dark_sky_icon","clear-day") %} Clear 
                         {% elif is_state("sensor.dark_sky_icon","clear-night") %} Clear 
                         {% elif is_state("sensor.dark_sky_icon","rain") %} Rain
                         {% elif is_state("sensor.dark_sky_icon","snow") %} Snowy
                         {% elif is_state("sensor.dark_sky_icon","fog") %} Foggy
                         {% elif is_state("sensor.dark_sky_icon","sleet") %} Sleet
                         {% elif is_state("sensor.dark_sky_icon","wind") %} Windy
                         {% elif is_state("sensor.dark_sky_icon","cloudy") %} Cloudy
                         {% elif is_state("sensor.dark_sky_icon","partly-cloudy-day") %} Partly Cloudy
                         {% elif is_state("sensor.dark_sky_icon","partly-cloudy-night") %} Partly Cloudy
                         {% elif is_state("sensor.dark_sky_icon","hail") %} Hailing
                         {% elif is_state("sensor.dark_sky_icon","lightning") %} Lightning
                         {% elif is_state("sensor.dark_sky_icon","thunderstorm") %} Thunderstorm
                         {% endif %}'

###############################################################################
# Customize History Entries
history:
  include:
    entities:
      
      # Include Current Sensors
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_humidity
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_pressure
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_visibility
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed

  exclude:
    entities:

      # Exclude Non-Measurables
      - sensor.dark_sky_current_text
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_icon
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_summary

      # Exclude Forecast Sensors
      - sensor.dark_sky_daily_max_precip_intensity_0d
      - sensor.dark_sky_daily_max_precip_intensity_1d
      - sensor.dark_sky_daily_max_precip_intensity_2d
      - sensor.dark_sky_daily_max_precip_intensity_3d
      - sensor.dark_sky_daily_max_precip_intensity_4d
      - sensor.dark_sky_daily_max_precip_intensity_5d
      - sensor.dark_sky_daytime_high_apparent_temperature_0d
      - sensor.dark_sky_daytime_high_apparent_temperature_1d
      - sensor.dark_sky_daytime_high_apparent_temperature_2d
      - sensor.dark_sky_daytime_high_apparent_temperature_3d
      - sensor.dark_sky_daytime_high_apparent_temperature_4d
      - sensor.dark_sky_daytime_high_apparent_temperature_5d
      - sensor.dark_sky_daytime_high_temperature_0d
      - sensor.dark_sky_daytime_high_temperature_1d
      - sensor.dark_sky_daytime_high_temperature_2d
      - sensor.dark_sky_daytime_high_temperature_3d
      - sensor.dark_sky_daytime_high_temperature_4d
      - sensor.dark_sky_daytime_high_temperature_5d
      - sensor.dark_sky_humidity_0d
      - sensor.dark_sky_humidity_1d
      - sensor.dark_sky_humidity_2d
      - sensor.dark_sky_humidity_3d
      - sensor.dark_sky_humidity_4d
      - sensor.dark_sky_humidity_5d
      - sensor.dark_sky_icon_0d
      - sensor.dark_sky_icon_1d
      - sensor.dark_sky_icon_2d
      - sensor.dark_sky_icon_3d
      - sensor.dark_sky_icon_4d
      - sensor.dark_sky_icon_5d
      - sensor.dark_sky_overnight_low_apparent_temperature_0d
      - sensor.dark_sky_overnight_low_apparent_temperature_1d
      - sensor.dark_sky_overnight_low_apparent_temperature_2d
      - sensor.dark_sky_overnight_low_apparent_temperature_3d
      - sensor.dark_sky_overnight_low_apparent_temperature_4d
      - sensor.dark_sky_overnight_low_apparent_temperature_5d
      - sensor.dark_sky_overnight_low_temperature_0d
      - sensor.dark_sky_overnight_low_temperature_1d
      - sensor.dark_sky_overnight_low_temperature_2d
      - sensor.dark_sky_overnight_low_temperature_3d
      - sensor.dark_sky_overnight_low_temperature_4d
      - sensor.dark_sky_overnight_low_temperature_5d
      - sensor.dark_sky_precip_0d
      - sensor.dark_sky_precip_1d
      - sensor.dark_sky_precip_2d
      - sensor.dark_sky_precip_3d
      - sensor.dark_sky_precip_4d
      - sensor.dark_sky_precip_5d
      - sensor.dark_sky_precip_accumulation_0d
      - sensor.dark_sky_precip_accumulation_1d
      - sensor.dark_sky_precip_accumulation_2d
      - sensor.dark_sky_precip_accumulation_3d
      - sensor.dark_sky_precip_accumulation_4d
      - sensor.dark_sky_precip_accumulation_5d
      - sensor.dark_sky_precip_intensity_0d
      - sensor.dark_sky_precip_intensity_1d
      - sensor.dark_sky_precip_intensity_2d
      - sensor.dark_sky_precip_intensity_3d
      - sensor.dark_sky_precip_intensity_4d
      - sensor.dark_sky_precip_intensity_5d
      - sensor.dark_sky_precip_probability_0d
      - sensor.dark_sky_precip_probability_1d
      - sensor.dark_sky_precip_probability_2d
      - sensor.dark_sky_precip_probability_3d
      - sensor.dark_sky_precip_probability_4d
      - sensor.dark_sky_precip_probability_5d
      - sensor.dark_sky_pressure_0d
      - sensor.dark_sky_pressure_1d
      - sensor.dark_sky_pressure_2d
      - sensor.dark_sky_pressure_3d
      - sensor.dark_sky_pressure_4d
      - sensor.dark_sky_pressure_5d
      - sensor.dark_sky_summary_0d
      - sensor.dark_sky_summary_1d
      - sensor.dark_sky_summary_2d
      - sensor.dark_sky_summary_3d
      - sensor.dark_sky_summary_4d
      - sensor.dark_sky_summary_5d
      - sensor.dark_sky_uv_index_0d
      - sensor.dark_sky_uv_index_1d
      - sensor.dark_sky_uv_index_2d
      - sensor.dark_sky_uv_index_3d
      - sensor.dark_sky_uv_index_4d
      - sensor.dark_sky_uv_index_5d
      - sensor.dark_sky_visibility_0d
      - sensor.dark_sky_visibility_1d
      - sensor.dark_sky_visibility_2d
      - sensor.dark_sky_visibility_3d
      - sensor.dark_sky_visibility_4d
      - sensor.dark_sky_visibility_5d
      - sensor.dark_sky_wind_bearing_0d
      - sensor.dark_sky_wind_bearing_1d
      - sensor.dark_sky_wind_bearing_2d
      - sensor.dark_sky_wind_bearing_3d
      - sensor.dark_sky_wind_bearing_4d
      - sensor.dark_sky_wind_bearing_5d
      - sensor.dark_sky_wind_speed_0d
      - sensor.dark_sky_wind_speed_1d
      - sensor.dark_sky_wind_speed_2d
      - sensor.dark_sky_wind_speed_3d
      - sensor.dark_sky_wind_speed_4d
      - sensor.dark_sky_wind_speed_5d

