###############################################################################
# Presence Package for Home Assistant

###############################################################################
# Customization
homeassistant:
  customize:

    # Presence Sensors
    binary_sensor.jp_presence:
      friendly_name: J.P.
      device_class: presence

    binary_sensor.jen_presence:
      friendly_name: Jen
      device_class: presence

    # People
    person.jpk:
      entity_picture: https://gravatar.com/avatar/e78e623948f3675cf1c51544f9bec928
    
    sensor.jp_presence_status:
      entity_picture: https://gravatar.com/avatar/e78e623948f3675cf1c51544f9bec928

    # Devices
    device_tracker.jp_n5x_ip:
      friendly_name: J.P. Nexus 5X
      icon: mdi:wifi
    device_tracker.jp_n5x_bt_entry:
      friendly_name: J.P. Nexus 5X
      source_type: bluetooth
      icon: mdi:bluetooth
    device_tracker.jp_n5x_gps:
      friendly_name: J.P. Nexus 5X
      icon: mdi:map-marker

    device_tracker.jp_gs8_ip:
      friendly_name: J.P. Galaxy S8
      icon: mdi:wifi
    device_tracker.jp_gs8_bt_entry:
      friendly_name: J.P. Galaxy S8
      source_type: bluetooth
      icon: mdi:bluetooth

    device_tracker.jen_iphone_ip:
      friendly_name: Jen iPhone
      icon: mdi:wifi
    device_tracker.jen_iphone_bt_entry:
      friendly_name: Jen iPhone
      source_type: bluetooth
      icon: mdi:bluetooth

    # RSSI Sensors
    sensor.jp_n5x_bt_rssi_raw_entry:
      hidden: true
    sensor.jp_n5x_bt_rssi_entry:
      friendly_name: J.P. Nexus 5X Bluetooth RSSI (Entry)
      hidden: true
    sensor.jp_gs8_bt_rssi_raw_entry:
      hidden: true
    sensor.jp_gs8_bt_rssi_entry:
      friendly_name: J.P. Galaxy S8 Bluetooth RSSI (Entry)
      hidden: true
    sensor.jen_iphone_bt_rssi_raw_entry:
      hidden: true
    sensor.jen_iphone_bt_rssi_entry:
      friendly_name: Jen iPhone RSSI (Entry)
      hidden: true

###############################################################################
# Device Trackers
person:
  - name: J.P.
    id: jpk
    user_id: c67b7b511277404995406e077e2f51ce
    device_trackers:
      - device_tracker.jp_n5x_ip
      - device_tracker.jp_n5x_bt_entry
      - device_tracker.jp_n5x_gps

  - name: Jen
    id: jen
    device_trackers:
      - device_tracker.jen_iphone_ip
      - device_tracker.jen_iphone_bt_entry

###############################################################################
# Device Trackers
device_tracker:

  # Ping Platform
  - platform: ping
    hosts:
      jp_n5x_ip: !secret jp_n5x_ip
      jp_gs8_ip: !secret jp_gs8_ip
      jen_iphone_ip: !secret jen_iphone_ip

  # MQTT Platform (Bluetooth Presence Sensor)
  - platform: mqtt
    devices:
      jp_n5x_bt_entry: monitor/entry/jp_n5x/device_tracker
      jp_gs8_bt_entry: monitor/entry/jp_gs8/device_tracker
      jen_iphone_bt_entry: monitor/entry/jen_iphone/device_tracker 

###############################################################################
# Input Selects for Extended Presence State
input_select:

  # J.P. Extended Presence State
  jp_presence_state:
    name: J.P.
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

  # Jen Extended Presence State
  jen_presence_state:
    name: Jen
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

  # Global House Presence
  house_presence_state:
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

###############################################################################
# Presence Sensors
sensor:

  # J.P. Extended Presence Status
  - platform: template
    sensors:
      jp_presence_status:
        value_template: '{{ states.input_select.jp_presence_state.state }}'
        friendly_name_template: 'J.P. Presence Status'

  # Jen Extended Presence Status
  - platform: template
    sensors:
      jen_presence_status:
        value_template: '{{ states.input_select.jen_presence_state.state }}'
        friendly_name_template: 'Jen Presence Status'

  # House Extended Presence Status
  - platform: template
    sensors:
      house_presence_status:
        value_template: '{{ states.input_select.house_presence_state.state }}'
        friendly_name_template: 'House Presence Status'

###############################################################################
# RSSI Sensors

  # Raw RSSI Data from Monitor
  - platform: mqtt
    name: jp_n5x_bt_rssi_raw_entry
    state_topic: monitor/entry/jp_n5x/rssi
    unit_of_measurement: 'dBm'

  - platform: mqtt
    name: jp_gs8_bt_rssi_raw_entry
    state_topic: monitor/entry/jp_gs8/rssi
    unit_of_measurement: 'dBm'

  - platform: mqtt
    name: jen_iphone_bt_rssi_raw_entry
    state_topic: monitor/entry/jp_n5x/rssi
    unit_of_measurement: 'dBm'

  # Filtered RSSI Data from Monitor
  - platform: filter
    name: jp_n5x_bt_rssi_entry
    entity_id: sensor.jp_n5x_bt_rssi_raw_entry
    filters:
      - filter: outlier
        window_size: 2
        radius: 1.0
      - filter: lowpass
        time_constant: 2
      - filter: time_simple_moving_average
        window_size: 00:01
        precision: 1

  - platform: filter
    name: jp_gs8_bt_rssi_entry
    entity_id: sensor.jp_gs8_bt_rssi_raw_entry
    filters:
      - filter: outlier
        window_size: 2
        radius: 1.0
      - filter: lowpass
        time_constant: 2
      - filter: time_simple_moving_average
        window_size: 00:01
        precision: 1

  - platform: filter
    name: jen_iphone_bt_rssi_entry
    entity_id: sensor.jen_iphone_bt_rssi_raw_entry
    filters:
      - filter: outlier
        window_size: 2
        radius: 1.0
      - filter: lowpass
        time_constant: 2
      - filter: time_simple_moving_average
        window_size: 00:01
        precision: 1

binary_sensor:
  # Bayesian Presence
  #- platform: bayesian
  #  prior: 0.5
  #  name: jp_presence
  #  probability_threshold: 0.75
  #  observations:
  #    - entity_id: device_tracker.jp_n5x_ip
  #      prob_given_true: 0.9
  #      prob_given_false: 0.3
  #      platform: state
  #      to_state: home
  #    - entity_id: device_tracker.jp_n5x_gps
  #      prob_given_true: 0.8
  #      prob_given_false: 0.2
  #      platform: state
  #      to_state: home
  #    - entity_id: device_tracker.jp_n5x_bt_entry
  #      prob_given_true: 0.8
  #      prob_given_false: 0.3
  #      platform: state
  #      to_state: home

  #- platform: bayesian
  #  prior: 0.5
  #  name: jen_presence
  #  probability_threshold: 0.75
  #  observations:
  #    - entity_id: device_tracker.jen_iphone_ip
  #      prob_given_true: 0.9
  #      prob_given_false: 0.3
  #      platform: state
  #      to_state: home
      #- entity_id: device_tracker.jen_iphone_bt_entry
      #  prob_given_true: 0.8
      #  prob_given_false: 0.3
      #  platform: state
      #  to_state: home

###############################################################################
# Presence Automations
automation:

###############################################################################
# Run Arrival Scan at Home Assistant Start
  
  - alias: Startup Arrival Scan
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: mqtt.publish
        data: 
          topic: monitor/scan/arrive
          payload: scan

###############################################################################
# Handle Just Arrived / Just Left from Person Entity

  - alias: Mark Person as Just Arrived
    trigger:
      - platform: state
        entity_id: person.jpk
        to: 'home'
      - platform: state
        entity_id: person.jen
        to: 'home'
    action:
      - service: input_select.select_option
        data_template: 
          entity_id: >
            {% if trigger.entity_id == 'person.jpk' %}
              input_select.jp_presence_state
            {% elif trigger.entity_id == 'person.jen' %}
              input_select.jen_presence_state
            {% else %}
            {% endif %}
          option: >
            {% if trigger.entity_id == 'person.jpk' %}
              {% if states.input_select.jp_presence_state == 'Just Left' %}
                Home
              {% else %}
                Just Arrived
              {% endif %}
            {% elif trigger.entity_id == 'person.jen' %}
              {% if states.input_select.jen_presence_state == 'Just Left' %}
                Home
              {% else %}
                Just Arrived
              {% endif %}
            {% else %}
            {% endif %}

  - alias: Mark Person as Just Left
    trigger:
      - platform: state
        entity_id: person.jpk
        from: 'home'
      - platform: state
        entity_id: person.jen
        from: 'home'
    action:
      - service: input_select.select_option
        data_template: 
          entity_id: >
            {% if trigger.entity_id == 'person.jpk' %}
              input_select.jp_presence_state
            {% elif trigger.entity_id == 'person.jen' %}
              input_select.jen_presence_state
            {% else %}
            {% endif %}
          option: 'Just Left'

###############################################################################
# Handle Timed Updates to Home / Away / Extended Away

  - alias: Mark Person as Home
    trigger:
      - platform: state
        entity_id: input_select.jp_presence_state
        to: 'Just Arrived'
        for: 
          minutes: 5
      - platform: state
        entity_id: input_select.jen_presence_state
        to: 'Just Arrived'
        for: 
          minutes: 5
    action:
      - service: input_select.select_option
        data_template: 
          entity_id: '{{ trigger.entity_id }}'
          option: 'Home'

  - alias: Mark Person as Away
    trigger:
      - platform: state
        entity_id: input_select.jp_presence_state
        to: 'Just Left'
        for: 
          minutes: 5
      - platform: state
        entity_id: input_select.jen_presence_state
        to: 'Just Left'
        for: 
          minutes: 5
    action:
      - service: input_select.select_option
        data_template: 
          entity_id: '{{ trigger.entity_id }}'
          option: 'Away'

  - alias: Mark Person as Extended Away
    trigger:
      - platform: state
        entity_id: input_select.jp_presence_state
        to: 'Away'
        for: 
          hours: 24
      - platform: state
        entity_id: input_select.jen_presence_state
        to: 'Away'
        for: 
          hours: 24
    action:
      - service: input_select.select_option
        data_template: 
          entity_id: '{{ trigger.entity_id }}'
          option: 'Extended Away'
