###############################################################################
# Presence Package for Home Assistant

###############################################################################
# Customization
homeassistant:
  customize:

    # Presence Sensors
    binary_sensor.jp_presence:
      friendly_name: J.P.
      device_class: presence

    binary_sensor.jen_presence:
      friendly_name: Jen
      device_class: presence

    # People
    sensor.jp_presence_status:
      entity_picture: https://gravatar.com/avatar/e78e623948f3675cf1c51544f9bec928

    # Devices
    device_tracker.monitor_entry_jp_n5x:
      friendly_name: J.P. Nexus 5X
      icon: mdi:bluetooth

    device_tracker.monitor_entry_jp_gs8:
      friendly_name: J.P. Galaxy S8
      icon: mdi:bluetooth

    device_tracker.monitor_entry_jen_iphone:
      friendly_name: Jen iPhone
      icon: mdi:bluetooth

###############################################################################
# Device Trackers
device_tracker:

  # MQTT Platform (Bluetooth Presence Sensor)
  - platform: mqtt
    devices:
      monitor_entry_jp_n5x: monitor/entry/jp_n5x/device_tracker
      monitor_entry_jp_gs8: monitor/entry/jp_gs8/device_tracker
      monitor_entry_jen_iphone: monitor/entry/jen_iphone/device_tracker 

# OwnTracks GPS Tracking
#owntracks:
#  max_gps_accuracy: 50
#  waypoints: true
#  mqtt_topic: 'owntracks/#'
#  events_only: false
#  waypoint_whitelist:
#    - jp
#  region_mapping:
#    Home: home
#    Work: work

# UniFi Integration Overrides
#unifi:
#  controllers:
#    - host: unifi.mgmt.kraussnet.com
#      site: !secret unifi_site
#      detection_time: 120
#      ssid_filter:
#        - !secret unifi_ssid_home

###############################################################################
# Input Selects for Extended Presence State
input_select:

  # J.P. Extended Presence State
  jp_presence_state:
    name: J.P.
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

  # Jen Extended Presence State
  jen_presence_state:
    name: Jen
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

  # Global House Presence
  house_presence_state:
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

###############################################################################
# Presence Sensors
sensor:

  # J.P. Extended Presence Status
  - platform: template
    sensors:
      jp_presence_status:
        value_template: '{{ states.input_select.jp_presence_state.state }}'
        friendly_name_template: 'J.P. Presence Status'

  # Jen Extended Presence Status
  - platform: template
    sensors:
      jen_presence_status:
        value_template: '{{ states.input_select.jen_presence_state.state }}'
        friendly_name_template: 'Jen Presence Status'

  # House Extended Presence Status
  - platform: template
    sensors:
      house_presence_status:
        value_template: '{{ states.input_select.house_presence_state.state }}'
        friendly_name_template: 'House Presence Status'

###############################################################################
# RSSI Sensors

  # Raw RSSI Data from Monitor
  - platform: mqtt
    name: monitor_entry_jp_n5x_rssi_raw
    state_topic: monitor/entry/jp_n5x/rssi
    unit_of_measurement: 'dBm'

  - platform: mqtt
    name: monitor_entry_jp_gs8_rssi_raw
    state_topic: monitor/entry/jp_gs8/rssi
    unit_of_measurement: 'dBm'

  - platform: mqtt
    name: monitor_entry_jen_iphone_rssi_raw
    state_topic: monitor/entry/jp_n5x/rssi
    unit_of_measurement: 'dBm'

  # Filtered RSSI Data from Monitor
  - platform: filter
    name: monitor_entry_jp_n5x_rssi
    entity_id: sensor.monitor_entry_jp_n5x_rssi_raw
    filters:
      - filter: outlier
        window_size: 2
        radius: 1.0
      - filter: lowpass
        time_constant: 2
      - filter: time_simple_moving_average
        window_size: 00:01
        precision: 1

  - platform: filter
    name: monitor_entry_jp_gs8_rssi
    entity_id: sensor.monitor_entry_jp_gs8_rssi_raw
    filters:
      - filter: outlier
        window_size: 2
        radius: 1.0
      - filter: lowpass
        time_constant: 2
      - filter: time_simple_moving_average
        window_size: 00:01
        precision: 1

  - platform: filter
    name: monitor_entry_jen_iphone_rssi
    entity_id: sensor.monitor_entry_jen_iphone_rssi_raw
    filters:
      - filter: outlier
        window_size: 2
        radius: 1.0
      - filter: lowpass
        time_constant: 2
      - filter: time_simple_moving_average
        window_size: 00:01
        precision: 1

binary_sensor:
  # Bayesian Presence
  - platform: bayesian
    prior: 0.5
    name: jp_presence
    probability_threshold: 0.75
    observations:
#      - entity_id: device_tracker.jp_n5x_ip
#        prob_given_true: 0.9
#        prob_given_false: 0.1
#        platform: state
#        to_state: home
#      - entity_id: device_tracker.jp_n5xot
#        prob_given_true: 0.7
#        prob_given_false: 0.2
#        platform: state
#        to_state: home
      - entity_id: device_tracker.monitor_entry_jp_n5x
        prob_given_true: 0.8
        prob_given_false: 0.3
        platform: state
        to_state: home

  - platform: bayesian
    prior: 0.5
    name: jen_presence
    probability_threshold: 0.75
    observations:
#      - entity_id: device_tracker.jen_iphone_ip
#        prob_given_true: 0.9
#        prob_given_false: 0.1
#        platform: state
#        to_state: home
      - entity_id: device_tracker.monitor_entry_jen_iphone
        prob_given_true: 0.8
        prob_given_false: 0.3
        platform: state
        to_state: home


###############################################################################
# Presence Automations
automation:

###############################################################################
# Handle Just Arrived / Just Left from Person Entity

  - alias: Mark Person as Just Arrived
    trigger:
      - platform: state
        entity_id: binary_sensor.jp_presence
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.jen_presence
        from: 'off'
        to: 'on'
    action:
      - service: input_select.select_option
        data_template: 
          entity_id: >
            {% if trigger.entity_id == 'binary_sensor.jp_presence' %}
              input_select.jp_presence_status
            {% elif trigger.entity_id == 'binary_sensor.jen_presence' %}
              input_select.jen_presence_status
            {% else %}
            {% endif %}
          option: >
            {% if trigger.entity_id == 'binary_sensor.jp_presence' %}
              {% if states.input_select.jp_presence_status == 'Just Left' %}
                Home
              {% else %}
                Just Arrived
              {% endif %}
            {% elif trigger.entity_id == 'binary_sensor.jen_presence' %}
              {% if states.input_select.jen_presence_status == 'Just Left' %}
                Home
              {% else %}
                Just Arrived
              {% endif %}
            {% else %}
            {% endif %}

  - alias: Mark Person as Just Left
    trigger:
      - platform: state
        entity_id: binary_sensor.jp_presence
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: binary_sensor.jen_presence
        from: 'on'
        to: 'off'
    action:
      - service: input_select.select_option
        data_template: 
          entity_id: >
            {% if trigger.entity_id == 'binary_sensor.jp_presence' %}
              input_select.jp_presence_status
            {% elif trigger.entity_id == 'binary_sensor.jen_presence' %}
              input_select.jen_presence_status
            {% else %}
            {% endif %}
          option: 'Just Left'

###############################################################################
# Handle Timed Updates to Home / Away / Extended Away

  - alias: Mark Person as Home
    trigger:
      - platform: state
        entity_id: input_select.jp_presence_status
        to: 'Just Arrived'
        for: 
          minutes: 5
      - platform: state
        entity_id: input_select.jen_presence_status
        to: 'Just Arrived'
        for: 
          minutes: 5
    action:
      - service: input_select.select_option
        data_template: 
          entity_id: '{{ trigger.entity_id }}'
          option: 'Home'

  - alias: Mark Person as Away
    trigger:
      - platform: state
        entity_id: input_select.jp_presence_status
        to: 'Just Left'
        for: 
          minutes: 5
      - platform: state
        entity_id: input_select.jen_presence_status
        to: 'Just Left'
        for: 
          minutes: 5
    action:
      - service: input_select.select_option
        data_template: 
          entity_id: '{{ trigger.entity_id }}'
          option: 'Away'

  - alias: Mark Person as Extended Away
    trigger:
      - platform: state
        entity_id: input_select.jp_presence_status
        to: 'Away'
        for: 
          days: 1
      - platform: state
        entity_id: input_select.jen_presence_status
        to: 'Away'
        for: 
          days: 1
    action:
      - service: input_select.select_option
        data_template: 
          entity_id: '{{ trigger.entity_id }}'
          option: 'Extended Away'
