###############################################################################
# Media Player Package for Home Assistant

###############################################################################
# Customization
homeassistant:
  customize:

    # Media Center Status Sensor
    sensor.media_center_status:
      icon: mdi:audio-video

    # Internal States
    input_select.ht_player_state:
      hidden: true
    input_select.ht_player_media:
      hidden: true
    input_select.ht_player_source:
      hidden: true
    input_select.ht_lighting_mode:
      hidden: true
    
    sensor.ht_player_state_state:
      hidden: true
    sensor.ht_player_media_state:
      hidden: true

###############################################################################
# Media Players
media_player:

  # Kodi Living Room TV
  #- platform: kodi
  #  name: Living Room OSMC
  #  host: 10.1.2.12
  #  port: 80

  # Jellyfin
  - platform: emby
    host: !secret jellyfin_host
    api_key: !secret jellyfin_api_key

  # Raspberry Pi Speakers
  - platform: mpd
    host: 10.1.2.42
    name: MPD Living Room

  # Snapcast Multi-Room Audio Server
  - platform: snapcast
    host: 10.1.4.20

# Roku Media Player
#roku:
#    host: 10.1.2.13

# Spotify (Main Account)
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret spotify_sp_dc
  sp_key: !secret spotify_sp_key

###############################################################################
# Inputs for Media Center State and Behavior
input_select:

  # Home Theater Player State
  ht_player_state:
    options:
      - Idle
      - Playing
      - Paused
      - Stopped
      - System
      - Offline
    initial: Idle

  # Home Theater Player Media Type
  ht_player_media:
    options:
      - TV
      - Movie
      - Music
      - Unknown
      - System
    initial: Unknown

  # Home Theater Player Source
  ht_player_source:
    options:
      - Kodi
      - FireTV
      - Roku
      - Unknown
    initial: Unknown

  # Home Theater Lighting Mode
  ht_lighting_mode:
    name: Theater Lighting Mode
    options:
      - Disabled        # Disables Media Lighting Automation
      - Normal          # Lights Off on Playing, Dim on Pause, No Change on Stopped
      - Dimmed          # Lights Dim on Playing/Pause, Raise on Stopped
    initial: Normal

input_boolean:

  ht_dim_on_play:
    name: 'Dim Lights on Media Playing'
    icon: mdi:movie

  ht_raise_on_pause:
    name: 'Raise Lights on Media Paused'
    icon: mdi:movie-outline

  ht_raise_on_stop:
    name: 'Raise Lights on Media Stopped'
    icon: mdi:movie-outline

  ht_reload_lights:
    name: 'Reload Home Theater Lights'
    icon: mdi:lightbulb-on-outline

###############################################################################
# Media Sensors
sensor:

  # Home Theater Player Status
  - platform: template
    sensors:
      ht_player_state_state:
        value_template: '{{ states.input_select.ht_player_state.state }}'
        friendly_name_template: 'Home Theater Player Status'

  # Home Theater Player Media
  - platform: template
    sensors:
      ht_player_media_state:
        value_template: '{{ states.input_select.ht_player_media.state }}'
        friendly_name_template: 'Home Theater Media Type'

###############################################################################
# Media Player Shell Scripts
shell_command:
  # Turn Home Theater TV On with HDMI CEC Helper
  ht_tv_on: /config/packages/media/tv_power.sh on

  # Turn Home Theater TV Off with HDMI CEC Helper
  ht_tv_off: /config/packages/media/tv_power.sh standby

###############################################################################
# Media Player Helper Scripts
script:

  # Set Home Theater Lighting Mode to Disabled
  ht_mode_set_disabled:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.ht_lighting_mode
          option: Disabled
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.ht_reload_lights
  
  # Set Home Theater Lighting Mode to Normal
  ht_mode_set_normal:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.ht_lighting_mode
          option: Normal
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.ht_reload_lights

  # Set Home Theater Lighting Mode to Dimmed
  ht_mode_set_dimmed:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.ht_lighting_mode
          option: Dimmed
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.ht_reload_lights

  # Turn on the Home Theater System
  ht_turn_on:
    description: Turn on the Home Theater
    fields:
      source:
        description: Roku Source to Active
        example: Netflix, Jellyfin Beta, Sling TV
    sequence:
      - service: shell_command.ht_tv_on

      - service: media_player.turn_on
        data:
          entity_id: media_player.home_theater

      - service: media_player.turn_on
        data:
          entity_id: media_player.roku

      - delay:
          seconds: 5

      - service: media_player.select_source
        data:
          entity_id: media_player.home_theater
          source: Roku

      - service: media_player.select_source
        data:
          entity_id: media_player.roku
          source: "{{ source }}"

  # Start a MPD Playlist on a Speaker
  speaker_play_mpd:
    description: Start an MPD Playlist on a Speaker
    fields:
      entity_id:
        description: MPD Entity Id
        example: media_player.mpd
      playlist:
        description: MPD Playlist Name
        example: Big Mix
    sequence:
      - service: media_player.play_media
        data:
          entity_id: "{{ entity_id }}"
          media_content_type: playlist
          media_content_id: "{{ playlist }}"

      - service: media_player.volume_set
        data:
          entity_id: "{{ entity_id }}"
          volume_level: 0.65
