# Manually Trigger Presence Departure Scan
- alias: Departure Scan
  trigger:
    - platform: state
      entity_id: input_boolean.departure_scan
      to: 'on'
  action:
    - service: mqtt.publish
      data:
        payload: zw_front_door
        topic: monitor/scan/DEPART
    - service: input_boolean.turn_off
      entity_id: input_boolean.departure_scan

# 5-ary Presence State Machine
- alias: Presence - Just Arrived
  trigger:
    - platform: state
      entity_id: binary_sensor.jp_presence
      from: 'off'
      to: 'on'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.jp_presence_status
        option: >
          {% if states.input_select.jp_presence_status.state == 'Just Left' %}
            Home
          {% else %}
            Just Arrived
          {% endif %}
- alias: Presence - Home
  trigger:
    - platform: state
      entity_id: input_select.jp_presence_status
      to: 'Just Arrived'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.jp_presence_status
        option: Home
- alias: Presence - Just Left
  trigger:
    - platform: state
      entity_id: binary_sensor.jp_presence
      from: 'on'
      to: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.jp_presence_status
        option: Just Left
- alias: Presence - Away
  trigger:
    - platform: state
      entity_id: input_select.jp_presence_status
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.jp_presence_status
        option: Away
- alias: Presence - Extended Away
  trigger:
    - platform: state
      entity_id: input_select.jp_presence_status
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.jp_presence_status
        option: Extended Away


- id: '1546488317587'
  alias: Media Player Stopped
  trigger:
  - entity_id: media_player.living_room_firetv
    from: playing
    platform: state
    to: standby
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: scene.living_room_normal
    service: scene.turn_on

- id: '1546488433417'
  alias: Media Player Started
  trigger:
  - entity_id: media_player.living_room_firetv
    from: standby
    platform: state
    to: playing
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: scene.living_room_dim
    service: scene.turn_on

- id: '1546550883902'
  alias: Nexus 5X Leaves Home
  trigger:
  - below: '20'
    entity_id: sensor.btp_entryway_jpk_nexus5x
    for: 0:00:10
    platform: numeric_state
  condition: []
  action:
  - data:
      message: bye lol
    service: notify.pushover
- id: '1546550943034'
  alias: Nexus 5X Arrives Home
  trigger:
  - above: '80'
    entity_id: sensor.btp_entryway_jpk_nexus5x
    for: 0:00:10
    platform: numeric_state
  condition: []
  action:
  - data:
      message: O HAI
    service: notify.pushover

- id: '1546577615833'
  alias: Media Center Idle
  trigger:
  - below: '10'
    entity_id: sensor.tplink_media_center_watts
    for: 0:00:10
    platform: numeric_state
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.media_center_state
      option: Idle

- id: '1546577737160'
  alias: Media Center TV
  trigger:
  - above: '20'
    below: '50'
    entity_id: sensor.tplink_media_center_watts
    for: 0:00:10
    platform: numeric_state
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.media_center_state
      option: TV

- id: '1546577815227'
  alias: Media Center Receiver
  trigger:
  - above: '60'
    below: '150'
    entity_id: sensor.tplink_media_center_watts
    for: 0:00:10
    platform: numeric_state
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.media_center_state
      option: Rcvr

- id: '1546577854908'
  alias: Media Center On
  trigger:
  - above: '160'
    entity_id: sensor.tplink_media_center_watts
    for: 0:00:10
    platform: numeric_state
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.media_center_state
      option: All
