#### Binary Sensor Definitions ################################################

# Bayesian Presence
- platform: bayesian
  prior: 0.5
  name: jp_presence
  probability_threshold: 0.85
  observations:
    - entity_id: device_tracker.jp_n5x_ip
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: state
      to_state: home
    - entity_id: device_tracker.jp_n5xot
      prob_given_true: 0.7
      prob_given_false: 0.2
      platform: state
      to_state: home
    - entity_id: sensor.monitor_entry_jp_n5x
      prob_given_true: 0.8
      prob_given_false: 0.3
      platform: numeric_state
      above: 80
