#### Group Definitions ########################################################

living_room:
  name: Living Room
  entities:
    - light.living_room_front
    - light.living_room_back
    - light.living_room_entry

bedroom:
  name: Bedroom
  entities:
    - light.bedroom_nightstand

automations:
  view: yes
  name: Automations
  icon: mdi:settings
  entities:
    - group.all_automations
