#### Group Definitions ########################################################

Living Room:
  entities:
    - light.living_room_main
    - light.hue_ambiance_lamp_1
    - light.hue_ambiance_lamp_2

Bedroom:
  entities:
    - light.hue_color_lamp_1
