#### Input Select Definitions #################################################

# Media Center State (based on power)
media_center_state:
  name: Media Center
  icon: mdi:audio-video
  options:
    - Idle
    - TV
    - Rcvr
    - All

# J.P. Extended Presence Status
jp_presence_status:
  name: J.P.
  options:
    - Home
    - Just Arrived
    - Just Left
    - Away
    - Extended Away
  initial: Home

# Home Theater Lighting Mode
ht_lighting_mode:
  name: Theater Lighting Mode
  options:
    - Disabled        # Disables Media Lighting Automation
    - TV Watching     # Dim Lights on Playing/Pause, Raise on Stopped
    - Cinema          # Lights Off on Playing, Dim on Pause, Low on Stopped
    - Date Night      # Lights Off on Playing, Dim on Pause, Off on Stopped
  initial: TV Watching
