#### Input Boolean Definitions ################################################

departure_scan:
  name: 'Trigger Departure Scan'
  initial: off
  icon: mdi:refresh

ht_dim_on_play:
  name: 'Dim Lights on Media Playing'
  icon: mdi:movie

ht_raise_on_pause:
  name: 'Raise Lights on Media Paused'
  icon: mdi:movie-outline

ht_raise_on_stop:
  name: 'Raise Lights on Media Stopped'
  icon: mdi:movie-outline

ht_auto_cinema_mode:
  name: 'Set Cinema Mode for Movies'
  icon: mdi:transition