#### Input Select Definitions #################################################

# J.P. Extended Presence Status
jp_presence_status:
  name: J.P.
  options:
    - Home
    - Just Arrived
    - Just Left
    - Away
    - Extended Away
  initial: Home

# Global House Mode
house_mode:
  options:
    - Morning
    - Day
    - Evening
    - Night
    - Sleep
  initial: Day

# Global House Presence
house_presence:
  options:
    - Home
    - Just Arrived
    - Just Left
    - Away
    - Extended Away
  initial: Home

# Global House Security
house_security:
  options:
    - Disarmed
    - Armed
    - Alarm
    - Silenced
  initial: Disarmed

# Home Theater Player State
ht_player_state:
  options:
    - Idle
    - Playing
    - Paused
    - Stopped
  initial: Idle

# Home Theater Player Media Type
ht_player_media:
  options:
    - TV
    - Movie
    - Music
    - Unknown
  initial: Unknown

# Home Theater Lighting Mode
ht_lighting_mode:
  name: Theater Lighting Mode
  options:
    - Disabled        # Disables Media Lighting Automation
    - Auto            # TV or Cinema depending on Media Type (TV or Movie)
    - TV              # Dim Lights on Playing/Pause, Raise on Stopped
    - Cinema          # Lights Off on Playing, Dim on Pause, Low on Stopped
    - Date Night      # Lights Off on Playing, Dim on Pause, Dim on Stopped
  initial: Auto
