#### Input Select Definitions #################################################

# Media Center State (based on power)
media_center_state:
  name: Media Center
  icon: mdi:audio-video
  options:
    - Idle
    - TV
    - Rcvr
    - All

# J.P. Extended Presence Status
jp_presence_status:
  name: J.P.
  options:
    - Home
    - Just Arrived
    - Just Left
    - Away
    - Extended Away
  initial: Home
