#### Scene Definitions ########################################################

- name: Living Room Normal
  entities:
    light.living_room_front:
      state: on
      transition: 5
      brightness_pct: 100
    light.living_room_back:
      state: on
      transition: 5
      brightness_pct: 100
    light.living_room_entry:
      state: on
      transition: 5
      brightness_pct: 100

- name: Living Room Dim
  entities:
    light.living_room_front:
      state: on
      transition: 5
      brightness_pct: 20
    light.living_room_back:
      state: on
      transition: 5
      brightness_pct: 20
    light.living_room_entry:
      state: on
      transition: 5
      brightness_pct: 20

- name: Dining Room Normal
  entities:
    light.dining_room_1:
      state: on
      brightness_pct: 100
      color_temp: 366
    light.dining_room_2:
      state: on
      brightness_pct: 100
      color_temp: 366
    light.dining_room_3:
      state: on
      brightness_pct: 100
      color_temp: 366