#### Scene Definitions ########################################################

- name: Living Room Normal
  entities:
    light.living_room_front:
      state: on
      transition: 5
      brightness_pct: 80
    light.living_room_back:
      state: on
      transition: 5
      brightness_pct: 80
    light.living_room_entry:
      state: on
      transition: 5
      brightness_pct: 80

- name: Living Room Dim
  entities:
    light.living_room_front:
      state: on
      transition: 5
      brightness_pct: 20
    light.living_room_back:
      state: on
      transition: 5
      brightness_pct: 20
    light.living_room_entry:
      state: on
      transition: 5
      brightness_pct: 20
