#### Script Definitions #######################################################

ht_mode_set_auto:
  # Set Home Theater Lighting Mode to Auto
  sequence:
    - service: input_select.select_option
      data:
        entity_id: input_select.ht_lighting_mode
        option: Auto
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.ht_reload_lights

ht_mode_set_date_night:
  # Set Home Theater Lighting Mode to Date Night
  sequence:
    - service: input_select.select_option
      data:
        entity_id: input_select.ht_lighting_mode
        option: Date Night
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.ht_reload_lights

ht_mode_set_cinema:
  # Set Home Theater Lighting Mode to Cinema
  sequence:
    - service: input_select.select_option
      data:
        entity_id: input_select.ht_lighting_mode
        option: Cinema
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.ht_reload_lights

ht_mode_set_tv:
  # Set Home Theater Lighting Mode to TV
  sequence:
    - service: input_select.select_option
      data:
        entity_id: input_select.ht_lighting_mode
        option: TV
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.ht_reload_lights

sunrise:
  # Simulated Sunrise on (House) Right Nightstand Lamp (30 min, from Off)
  sequence:
    # Dark Red
    - service: light.turn_on
      data:
        entity_id: light.nightstand_right
        xy_color: [0.67,0.39]
        brightness: 1
        transition: 60
    - delay:
        seconds: 60
    # Warm Orange
    - service: light.turn_on
      data:
        entity_id: light.nightstand_right
        xy_color: [0.65,0.41]
        brightness: 85
        transition: 600
    - delay:
        seconds: 600
    # Yellow
    - service: light.turn_on
      data:
        entity_id: light.nightstand_right
        xy_color: [0.60,0.40]
        brightness: 170
        transition: 600
    - delay:
        seconds: 600
    # White
    - service: light.turn_on
      data:
        entity_id: light.nightstand_right
        xy_color: [0.48,0.40]
        brightness: 255
        transition: 600
    - delay:
        seconds: 600

sunset:
  # Simulated Sunset on (House) Right Nightstand Lamp (10 min, from On)
  sequence:
    # Yellow
    - service: light.turn_on
      data:
        entity_id: light.nightstand_right
        xy_color: [0.60,0.40]
        brightness: 170
        transition: 180
    - delay:
        seconds: 180
    # Warm Orange
    - service: light.turn_on
      data:
        entity_id: light.nightstand_right
        xy_color: [0.65,0.41]
        brightness: 85
        transition: 180
    - delay:
        seconds: 180
    # Dark Red
    - service: light.turn_on
      data:
        entity_id: light.nightstand_right
        xy_color: [0.67,0.39]
        brightness: 1
        transition: 240
    - delay:
        seconds: 240
    # Off
    - service: light.turn_off
      entity_id: light.nightstand_right
