#### Switch Definitions #######################################################

# TP-Link TP-110 Switch/Power Monitors
- platform: tplink
  name: "TPLink Media Center"
  host: 10.2.1.231

- platform: tplink
  name: "TPLink Server Rack"
  host: 10.2.1.232