###############################################################################
# Indoor Air Quality Package for Home Assistant

###############################################################################
# Customization
homeassistant:
  customize:

###############################################################################
# IAQ Baseline Sensors Providers
sensor:

  # eCO2 Baseline
  - platform: mqtt
    state_topic: sensor/aq/000001c1793e/baseline
    unique_id: aq_000001c1793e_bl_eco2
    name: Baseline eCO2
    value_template: "{{ value_json.co2 }}"

  # TVOC Baseline
  - platform: mqtt
    state_topic: sensor/aq/000001c1793e/baseline
    unique_id: aq_000001c1793e_bl_tvoc
    name: Baseline TVOC
    value_template: "{{ value_json.tvoc }}"
