#### Sensor Definitions #######################################################

# Weather Prediction
- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - icon
    - summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - humidity
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - wind_speed
    - wind_bearing
    - precip_type
    - precip_probability
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - uv_index
    - daily_summary
    - pressure
    - visibility
  scan_interval:
    minutes: 5

# Dark Sky Current Condition
- platform: template
  sensors:
    dark_sky_current_text:
      value_template: '{% if is_state("sensor.dark_sky_icon","clear-day") %} Clear 
                       {% elif is_state("sensor.dark_sky_icon","clear-night") %} Clear 
                       {% elif is_state("sensor.dark_sky_icon","rain") %} Rain
                       {% elif is_state("sensor.dark_sky_icon","snow") %} Snowy
                       {% elif is_state("sensor.dark_sky_icon","fog") %} Foggy
                       {% elif is_state("sensor.dark_sky_icon","sleet") %} Sleet
                       {% elif is_state("sensor.dark_sky_icon","wind") %} Windy
                       {% elif is_state("sensor.dark_sky_icon","cloudy") %} Cloudy
                       {% elif is_state("sensor.dark_sky_icon","partly-cloudy-day") %} Partly Cloudy
                       {% elif is_state("sensor.dark_sky_icon","partly-cloudy-night") %} Partly Cloudy
                       {% elif is_state("sensor.dark_sky_icon","hail") %} Hailing
                       {% elif is_state("sensor.dark_sky_icon","lightning") %} Lightning
                       {% elif is_state("sensor.dark_sky_icon","thunderstorm") %} Thunderstorm
                       {% endif %}'

# Bluetooth Presence (JPK Nexus 5X at Entryway)
- platform: mqtt
  name: monitor_entry_jp_n5x
  state_topic: !secret monitor_entry_jp_n5x_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'

# ESP8266 Bed Sensors
- platform: mqtt
  state_topic: 'sensor/esp8266-bed-right'
  name: 'bed_right_value'

- platform: template
  sensors:
    jp_bed:
      friendly_name_template: "J.P. Bed"
      value_template: "{% if states('sensor.bed_right_value') | float > 300 %}Occupied{% else %}Empty{% endif %}"
      icon_template: "{% if states('sensor.bed_right_value') | float > 300 %}mdi:hotel{% else %}mdi:bed-empty{% endif %}"
