###############################################################################
# System Package for Home Assistant

###############################################################################
# Customization
homeassistant:
  customize:

    # UPS Sensors
    sensor.cyberpower_ups_battery_runtime:
      hidden: true
    sensor.cyberpower_ups_input_voltage:
      hidden: true
    sensor.cyberpower_ups_output_voltage:
      hidden: true
    sensor.cyberpower_ups_status:
      hidden: true
    sensor.cyberpower_ups_load:
      hidden: true

###############################################################################
# System Sensors
sensor:
  
  # NUT UPS Sensors
  - platform: nut
    name: CyberPower UPS
    host: localhost
    port: 3493
    alias: cp1000avr
    username: !secret ups_username # dummy: ups_user
    password: !secret ups_password # dummy: ups_pass
    resources:
      - ups.load
      - ups.status
      - ups.status.display
      - input.voltage
      - output.voltage
      - battery.runtime

  # Runtime in Minutes
  - platform: template
    sensors:
      cyberpower_ups_battery_runtime_mins:
        friendly_name: "CyberPower UPS Battery Runtime"
        value_template: "{{ (states('sensor.cyberpower_ups_battery_runtime')|float / 60 ) | round() }}"
        unit_of_measurement: 'Mins'
        icon: mdi:timer
